
version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: smca
    networks:
      - smca_net

  mosquitto:
    build: ./mqtt
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"     # Conexión sin TLS (opcional)
      - "8883:8883"     # Conexión segura MQTTs
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/certs:/mosquitto/certs
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - smca_net

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongo
      - mosquitto
    ports:
      - "3000:3000"
    volumes:
      - ./backend/certs:/app/certs
    env_file:
      - ./backend/.env
    networks:
      - smca_net


networks:
  smca_net:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
  mongo_data:
