
# ============================
# 📡 Mosquitto TLS Configuration
# ============================

listener 8883
protocol mqtt

# Certificados TLS
cafile /mosquitto/certs/ca/ca.crt
certfile /mosquitto/certs/server/server.crt
keyfile /mosquitto/certs/server/server.key

require_certificate false
# use_identity_as_username true

# Seguridad opcional
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl

# Logs
log_dest stdout
log_type all
